### ISSUE TITLE
Missing WAV Files

### ISSUE THREAD

**Issue by JohT** [JanWilczek/fir-simd#1]
Would you mind to include the WAV files `include/data/saw.wav` and `include/data/classroomImpulseResponse.wav` in your repository?

PS.: Thank you for the great video and these examples. 👍 This really helps to get into this topic much faster.

**Comment by JanWilczek** [comment]
Hi Johannes,

 

Thanks for the message. I may consider including these files, but the latter is licensed so I would need to include the source and the license… It’s pretty easy to find sample impulse responses in the internet 😊

 

Best regards,

Jan

 

From: Johannes 
Sent: Wednesday, June 1, 2022 8:09 AM
To: JanWilczek/fir-simd ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JanWilczek/fir-simd] Missing WAV Files (Issue #1)

 

Would you mind to include the WAV files include/data/saw.wav and include/data/classroomImpulseResponse.wav in your repository?

PS.: Thank you for the great video and these examples. 👍 This really helps to get into this topic much faster.

**Comment by JohT** [comment]
Thank you very much for your reply.

I could look up an impulse response that has an open source license, document/reference it accordingly and send you a pull request. I've found this repository that looks promising: https://github.com/RoyJames/room-impulse-responses 

If this is ok for you, I just need the specification of the wave files (length, mono?, sampling rate) I should look for, since they are used for benchmarking. I guess that "saw" is just a sawtooth wave? Of course I could also just make an educated guess.

Even if its not a big deal to just search for samples it would be very nice, if the build works out of the box without manual intervention.

**Comment by JanWilczek** [comment]
Hi Johannes,

 

The files were mono at 44.1 kHz. I’m sorry but I am not able to maintain every repo that I have while creating new content ☹

 

Best,

Jan

**Comment by JohT** [comment]
> I’m sorry but I am not able to maintain every repo that I have while creating new content.

I fully understand that. I am sorry that i bothered you. Keep on creating further great content. 👍

#### To summarize it for future reference:
- The last two lines in [CMakeLists.txt](https://github.com/JanWilczek/fir-simd/blob/master/CMakeLists.txt) show that the files `include/data/saw.wav` and `include/data/classroomImpulseResponse.wav` are required.  
- These file are missing on purpose to not get into trouble with licensing/copyright.
- Both files are assumed to be mono 44.1kHz wave files.
- There are plenty of resources online to get impulse responses. For example: https://github.com/RoyJames/room-impulse-responses

I'm fine with that so i'll set this issue to closed.

**Comment by JanWilczek** [comment]
Hi Johannes,

 

Thank you so much for your input and understanding! Thanks to you, other readers will be able to reproduce the results fully: I really appreciate and admire that!

 

Best regards,

Jan
